package Lecture_4;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.List;

public class HW4 {
    private WebDriver driver;

    @BeforeTest
    public void setUp() {
        driver = new ChromeDriver();
        driver.get("https://www.google.pl?hl=ru");
        driver.manage().window().setSize(new Dimension(1037, 807));
    }


    @Test(priority = 1)
    public void helloWorld() {
        driver.get("https://www.google.pl/");
        driver.findElement(By.id("L2AGLb")).click();
        driver.findElement(By.name("q")).clear();
        driver.findElement(By.name("q")).sendKeys("Привет, мир!");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        String foundText = driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).getText();
        Assert.assertTrue(foundText.toLowerCase().contains("Привет, мир".toLowerCase()));
//        String enteredText = driver.findElement(By.cssSelector("#cookie_button_submit > span")).getAttribute("value");
//        Assert.assertEquals(enteredText, "Привет, мир");
    }


    @Test(priority = 2)
    public void helloWorld2() {
        driver.get("https://www.google.pl/");
        driver.findElement(By.name("q")).clear();
        driver.findElement(By.name("q")).sendKeys("*//*");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        String enteredText = driver.findElement(By.id("rcnt")).getText();
        List<String> resultOptions = new ArrayList<>();
        resultOptions.add("Podana fraza - *//* - nie została odnaleziona.");
        resultOptions.add("Podpowiedzi:");
        resultOptions.add(" Sprawdź, czy wszystkie słowa zostały poprawnie napisane.");
        resultOptions.add(" Spróbuj użyć innych słów kluczowych.");
            resultOptions.add(" Spróbuj użyć bardziej ogólnych słów kluczowych.");
//        driver.findElement(By.cssSelector(".ssOUyb")).click();
    }

    @AfterTest
    public void tearDown() {
        driver.quit();
    }
}



