package Lecture_4;
// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class Lecture_4 {
    private WebDriver driver;

    @BeforeTest
    public void setUp() {
        driver = new ChromeDriver();
    }

    @AfterTest
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void passwordTest() {
        driver.get("https://www.sharelane.com/cgi-bin/register.py");
        driver.manage().window().setSize(new Dimension(1368, 912));
        driver.findElement(By.name("zip_code")).click();
        driver.findElement(By.name("zip_code")).sendKeys("12466677");
        driver.findElement(By.cssSelector("tr:nth-child(3) input")).click();
        driver.findElement(By.name("first_name")).click();
        driver.findElement(By.name("first_name")).sendKeys("1");
        driver.findElement(By.name("last_name")).click();
        driver.findElement(By.name("last_name")).sendKeys("2");
        driver.findElement(By.cssSelector("tr:nth-child(6) input")).click();
        driver.findElement(By.name("first_name")).sendKeys("name");
        driver.findElement(By.name("last_name")).sendKeys("name");
        driver.findElement(By.cssSelector("tr:nth-child(6) > td > input")).click();
        driver.findElement(By.name("password1")).click();
        Assert.assertEquals(driver.findElement(By.cssSelector(".error_message")).getText(),
                "Oops, error on page. Some of your fields have invalid data or email was previously used");
    }
}
